server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5433/made-for-maid-local
    username: anan
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: user_db
        default_batch_fetch_size: 100
