server:
  port: 8082

spring:
  application:
    name: made-for-maid.user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/made-for-maid-local
    username: anan
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: user_db

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
