### System Admin 생성
POST {{gatewayUrl}}/api/user/admin/system
Content-Type: application/json

{
  "accountId": "QtY0jrkJSeO",
  "nickname": "임아난 시스템 관리자",
  "systemSecret": "{{systemSecret}}"
}

### Shop Owner 생성
POST {{gatewayUrl}}/api/user/admin/owner
Content-Type: application/json

{
  "accountId": "QtY0jrkJSeO",
  "nickname": "임아난 사장님",
  "shopId": "shop_1"
}

### Shop Manager 생성
POST {{gatewayUrl}}/api/user/admin/manager
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Accept: application/json

{
  "accountId": "VI5KSsuIRY6",
  "nickname": "임아난 매니저4",
  "shopId": "shop_1"
}

### Shop Staff 생성
POST {{gatewayUrl}}/api/user/admin/maid
Content-Type: application/json

{
  "accountId": "QtY0jrkJSeO",
  "nickname": "샤라쨩",
  "shopId": "shop_1"
}

### 관리자 프로필 목록 조회
GET {{gatewayUrl}}/api/user/admin/profiles
Accept: application/json
Authorization: Bearer {{accessToken}}

### 관리자 프로필 선택
POST {{gatewayUrl}}/api/user/admin/profile/68j_JWEBQmm
Accept: application/json
Authorization: Bearer {{accessToken}}

### 관리자 조회
GET {{gatewayUrl}}/api/user/admin/search
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nicknameLike": null,
  "primaryRoles": ["SHOP_OWNER"],
  "staffType": null,
  "page": 0,
  "size": 10,
  "sort": "createdAt,desc"
}

### 관리자 승인 처리
POST {{gatewayUrl}}/api/user/admin/approve/nB7NamXhRN6
Authorization: Bearer {{accessToken}}

### 메이드/집사 조회
GET {{gatewayUrl}}/api/user/admin/staff/GFULekdmSEK
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 프로필 수정
POST {{gatewayUrl}}/api/user/admin/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "userId": "Vrc7ISk9Rna",
    "nickname": "올라",
    "profileImageId": "image_10",
    "profileImageUrl": "23424234"
}
