### 관리자 로그인 (카카오)
POST {{gatewayUrl}}/api/user/auth/admin/signin/kakao
Content-Type: application/json

{
  "oauthCode": "asfADjfa",
  "email": "tmdghks0615@gmail.com",
  "oauthId": "gasdfdsfas"
}

### System Admin 생성
POST {{gatewayUrl}}/api/user/auth/admin/system
Content-Type: application/json

{
  "accountId": "QtY0jrkJSeO",
  "nickname": "임아난 시스템 관리자",
  "systemSecret": "{{systemSecret}}"
}

### Cafe Owner 생성
POST {{gatewayUrl}}/api/user/auth/admin/owner
Content-Type: application/json

{
  "accountId": "QtY0jrkJSeO",
  "nickname": "임아난 사장님",
  "cafeId": "cafe_1"
}

### Cafe Manager 생성
POST {{gatewayUrl}}/api/user/auth/admin/manager
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Accept: application/json

{
  "accountId": "VI5KSsuIRY6",
  "nickname": "임아난 매니저4",
  "cafeId": "cafe_4"
}

### Cafe Staff 생성
POST {{gatewayUrl}}/api/user/auth/admin/maid
Content-Type: application/json

{
  "accountId": "QtY0jrkJSeO",
  "nickname": "샤라쨩",
  "cafeId": "cafe_1"
}
