### 회원가입
POST http://localhost:8082/api/auth/signup/kakao
Content-Type: application/json

{
  "email": "tmdghks2515@naver.com",
  "oauthId": "1234567890"
}


### 사용자 생성
POST http://localhost:8082/api/auth/user
Content-Type: application/json

{
    "accountId": "ljdNZg6_QIa",
    "nickname": "임아난",
    "maidCafeId": "1"
}
