### 카카오 로그인/회원가입
POST http://localhost:8080/api/user/auth/signin/user/kakao
Content-Type: application/json

{
  "oauthCode": "asfADjfa",
  "email": "tmdghks2515@naver.com",
  "oauthId": "aS2as4fF"
}

### 사용자 생성
POST http://localhost:8080/api/user/auth/user
Content-Type: application/json

{
  "accountId": "tNyKSNixSEi",
  "nickname": "임아난",
  "maidCafeId": "1"
}
